### ISSUE TITLE
Start implementing JS-based Ionic components

### ISSUE THREAD

**Issue by ebryn** [ebryn/ember-ionic#4]
Ionic is both a CSS framework & a set of AngularJS-based directives. I'd like to rebuild the AngularJS functionality using Ember best practices. We'll likely want to use [HammerJS](http://hammerjs.github.io/) for touch event handling & [Liquid Fire](http://ef4.github.io/liquid-fire/) for animations.

JS-based components to implement, roughly in priority order:
- [x] [ion-list](http://ionicframework.com/docs/api/directive/ionList/): see #13
- [x] [ion-side-menus](http://ionicframework.com/docs/api/directive/ionSideMenus/)
- [x] [ion-tabs](http://ionicframework.com/docs/api/directive/ionTabs/): see #15
- [x] [ion-slide-box](http://ionicframework.com/docs/api/directive/ionSlideBox/): see #14
- [ ] navigation
  - [ ] [ion-nav-view](http://ionicframework.com/docs/api/directive/ionNavView/)
  - [ ] [ion-view](http://ionicframework.com/docs/api/directive/ionView/)
  - [ ] [ion-nav-bar](http://ionicframework.com/docs/api/directive/ionNavBar/)
  - [ ] buttons?
- [x] [ion-loading](http://ionicframework.com/docs/api/service/$ionicLoading/)
- [ ] [ion-modal](http://ionicframework.com/docs/api/service/$ionicModal/)
- [ ] [ion-popover](http://ionicframework.com/docs/api/service/$ionicPopover/)
- [ ] [ion-popup](http://ionicframework.com/docs/api/service/$ionicPopup/)
- [ ] [ion-action-sheet](http://ionicframework.com/docs/api/service/$ionicActionSheet/)
- [ ] [ion-refresher](http://ionicframework.com/docs/api/directive/ionRefresher/)
- [ ] [ion-scroll](http://ionicframework.com/docs/api/directive/ionScroll/)
- [ ] [ion-infinite-scroll](http://ionicframework.com/docs/api/directive/ionInfiniteScroll/)

**Comment by Suven** [comment]
Could you guide me to the commits regarding the side-menu? How do you wire it with a button?
